spring:
  application:
    name: JwtImplementation

  datasource:
    url: jdbc:h2:mem:jwt_test
    driver-class-name: org.h2.Driver
    username: admin
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  app:
    security:
      jwt:
        secret: "K3lF7QAspsGG09mbIaryP3jtRkkxC5pwTV6BtM4kU5EXYRDEkMM9dUdjlpjPrEWYM"
        expiration: 1440000